# Generated by Django 3.2.8 on 2021-10-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='priority',
            field=models.CharField(choices=[(1, 'Nejvyšší'), (2, 'Vysoká'), (3, 'Střední'), (4, 'Nízká'), (5, 'Nejnižší')], default=3, max_length=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default=3, upload_to='.'),
            preserve_default=False,
        ),
    ]
