# Generated by Django 3.2.8 on 2022-01-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220118_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='photo_date',
        ),
        migrations.AddField(
            model_name='post',
            name='photo_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
